# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.CharField(max_length=15)),
                ('width', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_choice', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teresas_art.Genre'),
        ),
    ]
