# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teresas_art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='medium',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teresas_art.Genre'),
        ),
    ]
