# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teresas_art', '0002_auto_20161005_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='date_created',
        ),
        migrations.AddField(
            model_name='artwork',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
