# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teresas_art', '0003_auto_20161006_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_made', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='genre',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teresas_art.Year'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
