# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teresas_art', '0004_auto_20161006_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.TextField(blank=True, max_length=4000, null=True)),
                ('about', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='artwork',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
